# Generated by Django 5.2.3 on 2026-08-17 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEnrollmentState',
            fields=[
                ('vin', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False)),
                ('current_step', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('awaiting_async', 'Awaiting Async Response'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('tries', models.IntegerField(default=0)),
                ('max_tries', models.IntegerField(default=3)),
                ('step_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vehicle Enrollment State',
                'verbose_name_plural': 'Vehicle Enrollment States',
                'db_table': 'vehicle_enrollment_state',
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workflow Definition',
                'verbose_name_plural': 'Workflow Definitions',
                'db_table': 'workflow_definition',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(blank=True, max_length=50)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='enrollment.vehicleenrollmentstate')),
            ],
            options={
                'db_table': 'enrollment_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AsyncEnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=100)),
                ('products', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='async_requests', to='enrollment.vehicleenrollmentstate')),
            ],
            options={
                'verbose_name': 'Async Enrollment Request',
                'verbose_name_plural': 'Async Enrollment Requests',
                'db_table': 'async_enrollment_request',
            },
        ),
        migrations.AddField(
            model_name='vehicleenrollmentstate',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='enrollment.workflowdefinition'),
        ),
        migrations.CreateModel(
            name='WorkflowSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_step', models.CharField(max_length=50)),
                ('to_step', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('always', 'Always'), ('on_success', 'On Success'), ('on_failure', 'On Failure')], default='always', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='enrollment.workflowdefinition')),
            ],
            options={
                'db_table': 'workflow_sequence',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('step_type', models.CharField(choices=[('sync', 'Synchronous'), ('async', 'Asynchronous')], default='sync', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('api_endpoint', models.CharField(max_length=255)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('products', models.JSONField(blank=True, default=list)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('retryable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='enrollment.workflowdefinition')),
            ],
            options={
                'db_table': 'workflow_step',
                'ordering': ['order'],
                'unique_together': {('workflow', 'name')},
            },
        ),
    ]
