# Generated by Django 5.2.3 on 2026-08-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncenrollmentrequest',
            name='completed_products',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='asyncenrollmentrequest',
            name='pending_products',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='asyncenrollmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('partial', 'Partial Success'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
